import XCTest
@testable import Phoenix

/// The Swift codec must agree with the C++ core byte for byte — these
/// fixtures were generated by the real core (tools/../core/protocol.cpp) and
/// pasted in, so a drift on either side fails here.
final class PhoenixProtocolTests: XCTestCase {

    /// (label, hex of the full encoded frame) produced by phoenix_core.
    private let cppFixtures: [(String, String)] = [
        ("assistantText", "A50101000A0053756E6E792C203232434996"),
        ("chunkFinal", "A50202020500646F6E652E2AA3"),
        ("nav", "A50303000C0004FA004D61726B657420537417D7"),
        ("clearAll", "A50404000100FF77A8"),
        ("brightness", "A50507000100807D8C"),
        ("ping", "A5060500010001B787"),
        ("ack", "A5400600020005005EB3"),
        ("button", "A54107000200020129C7"),
        ("battery", "A5420800030057AC0F9547"),
        ("emptyPayload", "A501090000002A48"),
        ("utf8", "A5010A000A00636166C3A920F09F94A5B5F1"),
        ("maxPayload", "A5010B00000278787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878781C84"),
    ]

    private func bytes(fromHex hex: String) -> [UInt8] {
        var out = [UInt8]()
        var idx = hex.startIndex
        while idx < hex.endIndex {
            let next = hex.index(idx, offsetBy: 2)
            out.append(UInt8(hex[idx..<next], radix: 16)!)
            idx = next
        }
        return out
    }

    func testCRCCheckValue() {
        // CRC-16/CCITT-FALSE check value, the canonical one from the spec.
        XCTAssertEqual(PhoenixProto.crc16(Array("123456789".utf8)), 0x29B1)
    }

    func testEncodingMatchesCppFixtures() throws {
        // Rebuild each fixture from the Swift side and compare bytes.
        var builders: [String: PhoenixFrame] = [
            "assistantText": {
                var f = PhoenixMessages.assistantText("Sunny, 22C"); f.seq = 1; return f
            }(),
            "chunkFinal": {
                var f = PhoenixMessages.assistantChunk("done.", final: true); f.seq = 2; return f
            }(),
            "nav": {
                var f = PhoenixMessages.navUpdate(.slightRight, meters: 250, street: "Market St")
                f.seq = 3; return f
            }(),
            "clearAll": {
                var f = PhoenixMessages.clear(PhoenixProto.clearAll); f.seq = 4; return f
            }(),
            "brightness": {
                var f = PhoenixMessages.setBrightness(128); f.seq = 7; return f
            }(),
            "ping": { var f = PhoenixMessages.ping(); f.seq = 5; return f }(),
            "ack": PhoenixFrame(type: .ack, seq: 6, payload: [5, 0]),
            "button": PhoenixFrame(type: .buttonEvent, seq: 7, payload: [2, 1]),
            "battery": PhoenixFrame(type: .batteryStatus, seq: 8, payload: [87, 0xAC, 0x0F]),
            "emptyPayload": {
                var f = PhoenixMessages.assistantText(""); f.seq = 9; return f
            }(),
            "utf8": {
                var f = PhoenixMessages.assistantText("caf\u{E9} \u{1F525}"); f.seq = 10; return f
            }(),
            "maxPayload": PhoenixFrame(type: .assistantText, seq: 11,
                                       payload: [UInt8](repeating: 0x78, count: 512)),
        ]

        for (label, hex) in cppFixtures {
            let frame = try XCTUnwrap(builders.removeValue(forKey: label), "no builder for \(label)")
            let encoded = try XCTUnwrap(frame.encoded(), "encode failed for \(label)")
            XCTAssertEqual(encoded, bytes(fromHex: hex), "byte mismatch for \(label)")
        }
        XCTAssertTrue(builders.isEmpty, "unused builders: \(builders.keys.sorted())")
    }

    func testDecodeFixturesRoundTrip() throws {
        let decoder = PhoenixStreamDecoder()
        for (_, hex) in cppFixtures { decoder.feed(bytes(fromHex: hex)) }
        var decoded = [PhoenixFrame]()
        while let f = decoder.poll() { decoded.append(f) }
        XCTAssertEqual(decoded.count, cppFixtures.count)
        XCTAssertEqual(decoder.stats.crcErrors, 0)
        XCTAssertEqual(decoder.stats.bytesDropped, 0)

        let nav = try XCTUnwrap(decoded.first { $0.type == .navUpdate })
        XCTAssertEqual(nav.payload[0], PhoenixProto.Maneuver.slightRight.rawValue)
        XCTAssertEqual(UInt16(nav.payload[1]) | (UInt16(nav.payload[2]) << 8), 250)
        XCTAssertEqual(String(decoding: nav.payload[3...], as: UTF8.self), "Market St")

        let battery = try XCTUnwrap(decoded.first { $0.type == .batteryStatus })
        let parsed = try XCTUnwrap(PhoenixMessages.parseBatteryStatus(battery))
        XCTAssertEqual(parsed.percent, 87)
        XCTAssertEqual(parsed.millivolts, 4012)
    }

    func testOverMaxPayloadRefusesToEncode() {
        let f = PhoenixFrame(type: .assistantText,
                             payload: [UInt8](repeating: 0x41, count: PhoenixProto.maxPayload + 1))
        XCTAssertNil(f.encoded())
    }

    // MARK: hostile input

    func testSplitAcrossEveryBoundary() throws {
        var frame = PhoenixMessages.assistantText("The pen is mightier")
        frame.seq = 3
        let bytes = try XCTUnwrap(frame.encoded())
        for cut in 1..<bytes.count {
            let decoder = PhoenixStreamDecoder()
            decoder.feed(Array(bytes[0..<cut]))
            XCTAssertNil(decoder.poll(), "emitted from a truncated frame at \(cut)")
            decoder.feed(Array(bytes[cut...]))
            let got = try XCTUnwrap(decoder.poll(), "lost the frame split at \(cut)")
            XCTAssertEqual(got, frame)
            XCTAssertNil(decoder.poll())
        }
    }

    func testByteAtATimeMatchesSingleFeed() throws {
        var all = [UInt8]()
        for (_, hex) in cppFixtures { all += bytes(fromHex: hex) }

        let bulk = PhoenixStreamDecoder()
        bulk.feed(all)
        var expected = [PhoenixFrame]()
        while let f = bulk.poll() { expected.append(f) }

        let drip = PhoenixStreamDecoder()
        var got = [PhoenixFrame]()
        for b in all {
            drip.feed([b])
            while let f = drip.poll() { got.append(f) }
        }
        XCTAssertEqual(got, expected)
    }

    func testGarbageBetweenFramesResyncs() throws {
        var frame = PhoenixMessages.ping()
        frame.seq = 9
        let good = try XCTUnwrap(frame.encoded())
        let junk: [UInt8] = [0x00, 0x11, 0xFF, 0x7E, 0x13]  // no start bytes
        let decoder = PhoenixStreamDecoder()
        decoder.feed(junk)
        decoder.feed(good)
        let got = try XCTUnwrap(decoder.poll())
        XCTAssertEqual(got, frame)
        XCTAssertEqual(decoder.stats.bytesDropped, junk.count)
    }

    func testCorruptedFrameNeverEmitsAndRecovers() throws {
        var original = PhoenixMessages.navUpdate(.left, meters: 1234, street: "Elm Street")
        original.seq = 42
        let clean = try XCTUnwrap(original.encoded())
        var sentinel = PhoenixMessages.ping()
        sentinel.seq = 77
        let sentinelBytes = try XCTUnwrap(sentinel.encoded())
        let filler = [UInt8](repeating: 0, count: 520)  // completes any claimed length

        for i in 0..<clean.count {
            var corrupt = clean
            corrupt[i] ^= 0x80
            let decoder = PhoenixStreamDecoder()
            decoder.feed(corrupt)
            decoder.feed(filler)
            decoder.feed(sentinelBytes)
            var sawSentinel = false
            while let f = decoder.poll() {
                XCTAssertNotEqual(f, original, "corrupted frame surfaced (byte \(i))")
                if f == sentinel { sawSentinel = true }
            }
            XCTAssertTrue(sawSentinel, "decoder wedged after corruption at byte \(i)")
        }
    }

    func testOversizeLengthResyncs() throws {
        // Header claiming 513 bytes of payload: invalid by construction.
        var stream: [UInt8] = [PhoenixProto.startByte, 0x01, 0x00, 0x00, 0x01, 0x02]
        var good = PhoenixMessages.ping()
        good.seq = 3
        stream += try XCTUnwrap(good.encoded())

        let decoder = PhoenixStreamDecoder()
        decoder.feed(stream)
        let got = try XCTUnwrap(decoder.poll())
        XCTAssertEqual(got, good)
        XCTAssertGreaterThanOrEqual(decoder.stats.oversizeLength, 1)
    }

    func testRandomGarbageNeverCrashes() throws {
        var rng = SystemRandomNumberGenerator()
        let decoder = PhoenixStreamDecoder()
        for _ in 0..<300 {
            let n = Int.random(in: 0...400, using: &rng)
            let junk = (0..<n).map { _ in UInt8.random(in: 0...255, using: &rng) }
            decoder.feed(junk)
            while decoder.poll() != nil {}
        }
        // Still functional: flush any half-claimed frame, then a real one decodes.
        decoder.feed([UInt8](repeating: 0, count: 520))
        while decoder.poll() != nil {}
        var probe = PhoenixMessages.ping()
        probe.seq = 1
        decoder.feed(try XCTUnwrap(probe.encoded()))
        decoder.feed(try XCTUnwrap(probe.encoded()))
        var sawProbe = false
        while let f = decoder.poll() {
            if f == probe { sawProbe = true }
        }
        XCTAssertTrue(sawProbe)
    }

    func testUnknownTypeIsDroppedButStreamSurvives() throws {
        // Type 0x99 is not in MsgType: structurally valid, dropped at decode.
        var raw: [UInt8] = [PhoenixProto.startByte, 0x99, 0x05, 0x00, 0x03, 0x00, 1, 2, 3]
        let crc = PhoenixProto.crc16(raw[1...])
        raw.append(UInt8(crc & 0xFF))
        raw.append(UInt8((crc >> 8) & 0xFF))

        var good = PhoenixMessages.ping()
        good.seq = 6
        let decoder = PhoenixStreamDecoder()
        decoder.feed(raw)
        decoder.feed(try XCTUnwrap(good.encoded()))
        let got = try XCTUnwrap(decoder.poll())
        XCTAssertEqual(got, good, "unknown type should not block later frames")
        XCTAssertNil(decoder.poll())
    }

    func testDescribeCoversEveryMessageType() {
        let samples: [PhoenixFrame] = [
            PhoenixMessages.assistantText("hi"),
            PhoenixMessages.assistantChunk("hi", final: true),
            PhoenixMessages.navUpdate(.uturn, meters: 90, street: "Main"),
            PhoenixMessages.clear(PhoenixProto.clearAll),
            PhoenixMessages.setBrightness(10),
            PhoenixMessages.ping(),
            PhoenixFrame(type: .ack, payload: [1, 0]),
            PhoenixFrame(type: .buttonEvent, payload: [2, 1]),
            PhoenixFrame(type: .batteryStatus, payload: [50, 0x9A, 0x0E]),
        ]
        for f in samples {
            XCTAssertFalse(PhoenixMessages.describe(f).isEmpty)
        }
    }
}
