#pragma once

// GENERATED by tools/gen_fonts.py from tools/fonts/*.txt — do not edit.
// Edit the ASCII-art sources and rerun the generator instead.

#include "phoenix/font.h"
#include "phoenix/framebuffer.h"

namespace phoenix {

extern const Font kFontBody;
extern const Font kFontClock;

extern const Sprite kIconBell;
extern const Sprite kIconBubble;
extern const Sprite kIconEnvelope;
extern const Sprite kIconCalendar;
extern const Sprite kIconPhone;
extern const Sprite kIconPhoneMissed;
extern const Sprite kIconVoicemail;
extern const Sprite kIconNews;
extern const Sprite kIconHeart;
extern const Sprite kIconDollar;
extern const Sprite kIconPin;
extern const Sprite kIconNote;
extern const Sprite kIconBle;
extern const Sprite kIconCheck;
extern const Sprite kIconCross;
extern const Sprite kIconSpark;
extern const Sprite kArrowStraight;
extern const Sprite kArrowLeft;
extern const Sprite kArrowRight;
extern const Sprite kArrowSlightLeft;
extern const Sprite kArrowSlightRight;
extern const Sprite kArrowSharpLeft;
extern const Sprite kArrowSharpRight;
extern const Sprite kArrowUturn;
extern const Sprite kArrowArrive;
extern const Sprite kFlameA;
extern const Sprite kFlameB;

}  // namespace phoenix
