#!/usr/bin/env bash
# Builds the Phoenix firmware for the Seeed XIAO nRF52840 with arduino-cli.
# Installs the Seeed board package and U8g2 if missing, syncs the portable
# core library into firmware/lib (single source of truth stays in core/),
# and compiles. No hardware required — compilation is the verification.
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

SEEED_URL="https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json"
FQBN="Seeeduino:nrf52:xiaonRF52840"
SKETCH="firmware/phoenix_fw"
LIBDIR="firmware/lib"

if ! command -v arduino-cli >/dev/null 2>&1; then
  echo "error: arduino-cli not found — install it first (brew install arduino-cli)" >&2
  exit 1
fi

echo "== board index / platform =="
arduino-cli core update-index --additional-urls "$SEEED_URL"
if ! arduino-cli core list | grep -q "^Seeeduino:nrf52 "; then
  arduino-cli core install Seeeduino:nrf52 --additional-urls "$SEEED_URL"
fi

echo "== libraries =="
if ! arduino-cli lib list 2>/dev/null | grep -q "^U8g2 "; then
  arduino-cli lib install "U8g2"
fi

echo "== sync portable core -> $LIBDIR/PhoenixCore =="
# The rendering/protocol core has exactly one home: core/. This copy is
# regenerated on every build and is gitignored.
rm -rf "$LIBDIR/PhoenixCore"
mkdir -p "$LIBDIR/PhoenixCore/src"
rsync -a core/include/ "$LIBDIR/PhoenixCore/src/"        # headers: src/phoenix/*.h
rsync -a core/src/ "$LIBDIR/PhoenixCore/src/impl/"       # sources (recursive build)
# arduino-cli detects a library by headers at the src/ root only; this
# umbrella makes `#include <PhoenixCore.h>` pull the whole portable core in.
cat > "$LIBDIR/PhoenixCore/src/PhoenixCore.h" <<'EOF'
// Umbrella header for arduino-cli library detection (generated by build.sh).
#pragma once
#include "phoenix/ancs.h"
#include "phoenix/battery.h"
#include "phoenix/datetime.h"
#include "phoenix/device.h"
#include "phoenix/font.h"
#include "phoenix/font_data.h"
#include "phoenix/framebuffer.h"
#include "phoenix/layout.h"
#include "phoenix/protocol.h"
#include "phoenix/screen_manager.h"
#include "phoenix/screens.h"
#include "phoenix/text_sanitize.h"
#include "phoenix/version.h"
EOF
cat > "$LIBDIR/PhoenixCore/library.properties" <<EOF
name=PhoenixCore
version=1.0.0
author=Project Phoenix
maintainer=Project Phoenix
sentence=Portable rendering, layout, ANCS model and protocol core for the Phoenix HUD.
paragraph=Synced from core/ by firmware/build.sh. Do not edit here.
category=Display
url=https://localhost/phoenix
architectures=*
EOF

echo "== compile =="
# The Arduino nRF52 platform defaults to gnu++11; the core is C++17
# (std::optional and friends), so append a later -std that overrides it.
arduino-cli compile \
  --fqbn "$FQBN" \
  --libraries "$LIBDIR" \
  --build-property "compiler.cpp.extra_flags=-std=gnu++17" \
  --warnings default \
  "$SKETCH"

echo "OK: firmware compiled clean for $FQBN"
